<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
  m1,n1=len(A),len(A[0])
  m2,n2=len(B).len(B[0])
  if n1 !=m2:
    print("Matrix multiplication not possible ")
    return
  result=[[0 for j in range(n2)] for i in range(m1)]
  for i in range(m1):
    for j in range(m2):
      for k in range(n2):
        result[i][j]+=A[i][j]*B[j][k]
  return result
    # write your code

matrix_mul(A, B)

<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

def pick_a_number_from_list(A):
  s=sum(A)
  A=A//s
  cum_sum=A[0]
  new_list=[cum_sum]
  for i in range(1,len(A)):
    cum_sum=cum_sum+A[i]
    new_list.append(cum_sum)
  r=random.uniform(0,1)
def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
  fs=re.sub('\D','',String)
  fs=re.sub('\d','#',fs)


    # write your code
    #
  return fs # modified string which is after replacing the # with digits
String='#2a$#b%c%561#'
replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a.
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    new_list=[]
    for i in range(len(students)):
      t=(students[i],marks[i])
      new_list.append(t)

    student_marks = sorted(new_list, key=lambda x:x[1])
    top_5_students=[(student, mark) for student, mark in reversed(student_marks[-5:])]


    # write code for computing top least 5 students
    least_5_students =student_marks[:5]
    # write code for computing top least 5 students
    students_within_25_and_75 = # compute this

    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
  distances=[]
  for ele in S:
    x_cord,y_cord=ele[0],ele[1]
    cos_angle=(x_cord*P[0])+(y_cord*P[1])/((math.sqrt((x_cord)**2+(y_cord)**2))* (math.sqrt((P[0])**2+(P[1])**2)))
    cos_angle = max(min(cos_angle, 1), -1)
    acos_angle = 0
    if cos_angle == 1:
        acos_angle = 0
    elif cos_angle == -1:
        acos_angle = math.pi
    else:
        # Using a simple approximation for acos
        acos_angle = math.pi / 2 - cos_angle
    distances.append((ele,acos_angle))
    closest_points=sorted(distances,key=lambda x:x[1])[:5]

    # write your code here
  return closest_points  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
for point in points:
  print(point[0],point[1])

(1, 2) 0
(3, 4) 0
(6, -7) 0
(6, 0) 0
(1, -1) 0


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
  line.strip()
  parts = line.split('x')
  x_coeff = int(parts[0])
  parts = parts[1].split('y')
  y_coeff = int(parts[0])
  if (parts[1][0]=='-'):
       const= -1* int(float(parts[1][1:]))
  else:
    const=int(float(parts[1][1:]))

  res=red[0][0]*x_coeff+red[0][1]*y_coeff+const
  if res>=0:
    pos_r=True
  else :
    pos_r=False
  for point in red[1:]:
    res=point[0]*x_coeff+point[1]*y_coeff+const

    if (res<0 and pos_r==True) or (res>=0 and pos_r==False):
      return 'No'

    else:
      continue

  res=blue[0][0]*x_coeff+blue[0][1]*y_coeff+const
  if res>=0:
    pos_b=True
  else:
      pos_b=False
  for point in blue[1:]:
    res=point[0]*x_coeff+point[1]*y_coeff+const

    if (res<0 and pos_b==True) or (res>=0 and pos_b==False):
      return 'No'
    else:
      continue
  if pos_r != pos_b:
    return "Yes"
  return "No"




    # your code


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print( yes_or_no) # the returned value

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _)
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex:
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
  pos=-1

  string=string.split(',')
  print(string)
  l=[0]*len(string)
  for i in range(len(string)):
    if string[i] =='_':
      continue
    else:
      if pos==-1:
        l[0:i+1:1]=[int(string[i])//len( string[:i+1]) for k in range(i+1) ]
        print(l)
        pos=i
      elif pos>-1:
        print(pos,i)
        l[pos:i+1]=[(int(string[i])+int(l[pos]))//len(string[pos:i+1]) for k in range(pos,i+1) ]
        pos=i
      else:
        continue
  if string[-1]=='_':
    print(string[pos])
    l[pos::]=[int(l[pos])//len(string[pos:]) for k in range(pos,i+1) ]

  return l



  return #list of values

#S=  "_,_,30,_,_,_,50,_,_"
S="80,_,_,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)# print above values)

['80', '_', '_', '_', '_']
[80, 0, 0, 0, 0]
80
[16, 16, 16, 16, 16]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex:
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
  words_S1 = set(S1.split())
  words_S2 = set(S2.split())

  # Find common words between S1 and S2
  common_words = words_S1.intersection(words_S2)

  # Find words in S1 but not in S2
  unique_words_S1 = words_S1.difference(words_S2)

  # Find words in S2 but not in S1
  unique_words_S2 = words_S2.difference(words_S1)

  # Output
  return (len(common_words), unique_words_S1, unique_words_S2)
    # your code


S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

7 {'F', '5', 'first'} {'3', 'S', 'second'}


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math
# you can free to change all these codes/structure
def compute_log_loss(A):
  n=len(A)
  logloss=0
  for ele in A:
    logloss=logloss+((ele[0]*(math.log(ele[1])/math.log(10)))+ ((1-ele[0])*(math.log(1-ele[1])/math.log(10))))
  return (-1*logloss)/n
    # your code


A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

-0.39794000867203755
-0.6989700043360187
-1.6989700043360187
-1.8538719643217618
-2.2518119729937993
-3.2518119729937993
-3.2975694635544746
-3.394479476562531
0.42430993457031635
